- id: context-headers
  name: Check/Add Context Headers
  description: Ensures files have a comment at the top indicating their path (useful for AI context).
  entry: context-headers
  language: python
  types: [text]
  # Files to exclude by default from all projects using this hook
  exclude: |
    (?x)^(
        package-lock\.json|
        poetry\.lock|
        yarn\.lock|
        .*\.min\.js|
        .*\.min\.css|
        .*\.svg|
        .*\.json|
        .*\.geojson|
        .*\.map
    )$
