# File: .pre-commit-hooks.yaml
- id: context-headers
  name: Check/Add Context Headers
  description: Ensures files have a comment at the top indicating their path (useful for AI context).
  entry: context-headers
  language: python
  types: [text]
  # Files to exclude by default from all projects using this hook
  # Note: This list explicitly duplicates config.py ALWAYS_SKIP_FILENAMES for performance.
  # We want pre-commit to filter these BEFORE spinning up the Python process.
  exclude: |
    (?x)^(
        package-lock\.json|
        yarn\.lock|
        pnpm-lock\.yaml|
        npm-shrinkwrap\.json|
        poetry\.lock|
        uv\.lock|
        Cargo\.lock|
        go\.sum|
        go\.mod|
        Gemfile\.lock|
        composer\.lock|
        mix\.lock|
        pubspec\.lock|
        Pipfile\.lock|
        bun\.lockb|
        deno\.lock|
        .*\.min\.js|
        .*\.min\.css|
        .*\.svg|
        .*\.json|
        .*\.geojson|
        .*\.map
    )$
