# File: src/context_headers/config.py
from __future__ import annotations

# Safety: Do not process files larger than this (1MB) to prevent hangs.
MAX_FILE_SIZE_BYTES = 1024 * 1024

# Configuration: Comment styles for various extensions.
COMMENT_STYLES: dict[str, str] = {
    ".sh": "# File: {}",
    ".bash": "# File: {}",
    ".bashrc": "# File: {}",
    ".bash_profile": "# File: {}",
    ".zsh": "# File: {}",
    ".zshrc": "# File: {}",
    ".fish": "# File: {}",
    ".ps1": "# File: {}",
    ".ps1": "<# File: {} #>",
    ".psm1": "# File: {}",
    ".psd1": "# File: {}",
    ".bat": "REM File: {}",
    ".bat": ":: File: {}",
    ".cmd": "REM File: {}",
    ".cmd": ":: File: {}",
    ".js": "// File: {}",
    ".js": "/* File: {} */",
    ".mjs": "// File: {}",
    ".mjs": "/* File: {} */",
    ".cjs": "// File: {}",
    ".ts": "// File: {}",
    ".ts": "/* File: {} */",
    ".mts": "// File: {}",
    ".cts": "// File: {}",
    ".html": "",
    ".htm": "",
    ".xhtml": "",
    ".css": "/* File: {} */",
    ".scss": "// File: {}",
    ".scss": "/* File: {} */",
    ".sass": "// File: {}",
    ".less": "// File: {}",
    ".less": "/* File: {} */",
    ".styl": "// File: {}",
    ".styl": "/* File: {} */",
    ".svelte": "",
    ".vue": "",
    ".vue": "// File: {}",
    ".jsx": "// File: {}",
    ".jsx": "{/* File: {} */}",
    ".tsx": "// File: {}",
    ".tsx": "{/* File: {} */}",
    ".wat": ";; File: {}",
    ".wat": "(; File: {} ;)",
    ".wasm": ";; File: {}",
    ".py": "# File: {}",
    ".py": '""" File: {} """',
    ".pyi": "# File: {}",
    ".pyw": "# File: {}",
    ".pyx": "# File: {}",
    ".java": "// File: {}",
    ".java": "/* File: {} */",
    ".jsp": "<%-- File: {} --%>",
    ".cs": "// File: {}",
    ".cs": "/* File: {} */",
    ".csx": "// File: {}",
    ".cpp": "// File: {}",
    ".cpp": "/* File: {} */",
    ".hpp": "// File: {}",
    ".hpp": "/* File: {} */",
    ".cc": "// File: {}",
    ".cc": "/* File: {} */",
    ".hh": "// File: {}",
    ".cxx": "// File: {}",
    ".hxx": "// File: {}",
    ".c": "/* File: {} */",
    ".h": "/* File: {} */",
    ".go": "// File: {}",
    ".go": "/* File: {} */",
    ".rs": "// File: {}",
    ".rs": "/* File: {} */",
    ".php": "// File: {}",
    ".php": "# File: {}",
    ".php": "/* File: {} */",
    ".phtml": "",
    ".rb": "# File: {}",
    ".rb": "=begin File: {} =end",
    ".rake": "# File: {}",
    ".gemspec": "# File: {}",
    ".swift": "// File: {}",
    ".swift": "/* File: {} */",
    ".kt": "// File: {}",
    ".kt": "/* File: {} */",
    ".kts": "// File: {}",
    ".dart": "// File: {}",
    ".dart": "/* File: {} */",
    ".ex": "# File: {}",
    ".exs": "# File: {}",
    ".erl": "% File: {}",
    ".hrl": "% File: {}",
    ".hs": "-- File: {}",
    ".hs": "{- File: {} -}",
    ".lhs": "> File: {}",
    ".nim": "# File: {}",
    ".nim": "#[ File: {} ]#",
    ".zig": "// File: {}",
    ".zig": "/// File: {}",
    ".v": "// File: {}",
    ".v": "/* File: {} */",
    ".jl": "# File: {}",
    ".jl": "#= File: {} =#",
    ".mojo": "# File: {}",
    ".🔥": "# File: {}",
    ".carbon": "// File: {}",
    ".cb": "// File: {}",
    ".odin": "// File: {}",
    ".odin": "/* File: {} */",
    ".gleam": "// File: {}",
    ".lean": "-- File: {}",
    ".lean": "/- File: {} -/",
    ".val": "// File: {}",
    ".hylo": "// File: {}",
    ".roc": "# File: {}",
    ".u": "-- File: {}",
    ".gr": "// File: {}",
    ".kk": "// File: {}",
    ".kk": "/* File: {} */",
    ".sw": "// File: {}",
    ".cairo": "// File: {}",
    ".nr": "// File: {}",
    ".tact": "// File: {}",
    ".move": "// File: {}",
    ".talon": "# File: {}",
    ".typ": "// File: {}",
    ".typ": "/* File: {} */",
    ".tf": "# File: {}",
    ".tf": "// File: {}",
    ".tf": "/* File: {} */",
    ".tfvars": "# File: {}",
    ".bicep": "// File: {}",
    ".bicep": "/* File: {} */",
    ".yaml": "# File: {}",
    ".yml": "# File: {}",
    ".toml": "# File: {}",
    ".json5": "// File: {}",
    ".json5": "/* File: {} */",
    ".sql": "-- File: {}",
    ".sql": "/* File: {} */",
    ".ddl": "-- File: {}",
    ".dml": "-- File: {}",
    ".prc": "-- File: {}",
    ".graphql": "# File: {}",
    ".gql": "# File: {}",
    ".prisma": "// File: {}",
    ".proto": "// File: {}",
    ".makefile": "# File: {}",
    ".m4": "dnl File: {}",
    ".lua": "-- File: {}",
    ".lua": "--[[ File: {} ]]",
    ".pl": "# File: {}",
    ".pm": "# File: {}",
    ".raku": "# File: {}",
    ".raku": "#` File: {} ",
    ".scala": "// File: {}",
    ".scala": "/* File: {} */",
    ".clj": "; File: {}",
    ".cljs": "; File: {}",
    ".lisp": "; File: {}",
    ".lisp": "#| File: {} |#",
    ".scm": "; File: {}",
    ".f90": "! File: {}",
    ".m": "% File: {}",
    ".m": "%{ File: {} %}",
    ".sas": "* File: {}",
    ".sas": "/* File: {} */",
    ".st": '" File: {} "',
    ".pas": "// File: {}",
    ".pas": "{ File: {} }",
    ".pas": "(* File: {} *)",
    ".r": "# File: {}",
    ".tcl": "# File: {}",
    ".awk": "# File: {}",
    ".sed": "# File: {}",
    ".ini": "; File: {}",
    ".ini": "# File: {}",
    ".conf": "# File: {}",
    ".vhd": "-- File: {}",
    ".sv": "// File: {}",
    ".sv": "/* File: {} */",
    ".asm": "; File: {}",
    ".s": "; File: {}",
    ".s": "@ File: {}",
    ".tex": "% File: {}",
    ".md": "",
    ".rst": ".. File: {}",
    ".adoc": "// File: {}",
    ".d": "// File: {}",
    ".d": "/* File: {} */",
    ".d": "/+ File: {} +/",
    ".cls": "// File: {}",
    ".coffee": "# File: {}",
    ".coffee": "### File: {} ###",
    ".feature": "# File: {}",
    ".hbs": "{{!-- File: {} --}}",
    ".jade": "// File: {}",
    ".pug": "// File: {}",
    ".twig": "{# File: {} #}",
    ".mustache": "{{! File: {} }}",
    ".razor": "@* File: {} *@ ",
    ".inc": "// File: {}",
    ".ino": "// File: {}",
    ".cl": "// File: {}",
    ".cu": "// File: {}",
    ".mm": "// File: {}",
    ".mm": "/* File: {} */",
    ".f": "! File: {}",
    ".for": "C File: {}",
    ".adb": "-- File: {}",
    ".ads": "-- File: {}",
    ".agda": "-- File: {}",
    ".agda": "{- File: {} -}",
    ".als": "// File: {}",
    ".als": "-- File: {}",
    ".ampl": "# File: {}",
    ".as": "// File: {}",
    ".as": "/* File: {} */",
    ".asy": "// File: {}",
    ".aug": "(* File: {} *)",
    ".ahk": "; File: {}",
    ".au3": "; File: {}",
    ".au3": "#comments-start File: {} ",
    ".bb": "# File: {}",
    ".bcpl": "// File: {}",
    ".bsh": "// File: {}",
    ".brs": "' File: {}",
    ".brs": "REM File: {}",
    ".chs": "-- File: {}",
    ".cmake": "# File: {}",
    ".cmake": "#[[ File: {} ]]",
    ".cob": "* File: {}",
    ".cbl": "* File: {}",
    ".cfm": "",
    ".clp": "; File: {}",
    ".coq": "(* File: {} *)",
    ".curry": "-- File: {}",
    ".cy": "// File: {}",
    ".dhall": "-- File: {}",
    ".dylan": "// File: {}",
    ".e": "# File: {}",
    ".ebnf": "(* File: {} *)",
    ".ec": "// File: {}",
    ".ecl": "// File: {}",
    ".elm": "-- File: {}",
    ".el": "; File: {}",
    ".factor": "! File: {}",
    ".fy": "# File: {}",
    ".fan": "// File: {}",
    ".flow": "// File: {}",
    ".fth": "\\ File: {}",
    ".fth": "( File: {} )",
    ".fut": "-- File: {}",
    ".g4": "// File: {}",
    ".gap": "# File: {}",
    ".gd": "# File: {}",
    ".glsl": "// File: {}",
    ".vert": "// File: {}",
    ".frag": "// File: {}",
    ".gs": "// File: {}",
    ".hack": "// File: {}",
    ".hx": "// File: {}",
    ".hx": "/* File: {} */",
    ".idr": "-- File: {}",
    ".ni": "[ File: {} ]",
    ".iss": "; File: {}",
    ".io": "// File: {}",
    ".io": "# File: {}",
    ".ik": "; File: {}",
    ".thy": "(* File: {} *)",
    ".ijs": "NB. File: {}",
    ".jcl": "//* File: {}",
    ".krl": "; File: {}",
    ".lasso": "// File: {}",
    ".lasso": "# File: {}",
    ".ly": "% File: {}",
    ".ls": "# File: {}",
    ".ll": "; File: {}",
    ".logo": "; File: {}",
    ".lgt": "% File: {}",
    ".mako": "## File: {}",
    ".mel": "// File: {}",
    ".meson": "# File: {}",
    ".minid": "// File: {}",
    ".mo": "// File: {}",
    ".mod": "(* File: {} *)",
    ".moon": "-- File: {}",
    ".mq4": "// File: {}",
    ".mq5": "// File: {}",
    ".mtml": "<$# File: {} #$>",
    ".n": "// File: {}",
    ".axs": "// File: {}",
    ".nlogo": "; File: {}",
    ".ns2": '" File: {} "',
    ".nf": "// File: {}",
    ".nsi": "; File: {}",
    ".nu": "; File: {}",
    ".obj": "# File: {}",
    ".j": "// File: {}",
    ".ooc": "// File: {}",
    ".opa": "// File: {}",
    ".p4": "// File: {}",
    ".pan": "# File: {}",
    ".psc": "; File: {}",
    ".pir": "# File: {}",
    ".pwn": "// File: {}",
    ".pep": "; File: {}",
    ".pico": "// File: {}",
    ".pig": "-- File: {}",
    ".pike": "// File: {}",
    ".pli": "/* File: {} */",
    ".pls": "-- File: {}",
    ".pony": "// File: {}",
    ".ps": "% File: {}",
    ".pov": "// File: {}",
    ".pbl": "// File: {}",
    ".pde": "// File: {}",
    ".pml": "/* File: {} */",
    ".pb": "; File: {}",
    ".purs": "-- File: {}",
    ".arr": "# File: {}",
    ".q": "/ File: {}",
    ".qs": "// File: {}",
    ".qml": "// File: {}",
    ".qc": "// File: {}",
    ".rkt": "; File: {}",
    ".raml": "# File: {}",
    ".rsc": "// File: {}",
    ".ratfor": "# File: {}",
    ".red": "; File: {}",
    ".cw": "; File: {}",
    ".rpy": "# File: {}",
    ".rexx": "/* File: {} */",
    ".ring": "# File: {}",
    ".rg": "// File: {}",
    ".x": "/* File: {} */",
    ".spec": "# File: {}",
    ".sci": "// File: {}",
    ".self": '" File: {} "',
    ".shader": "// File: {}",
    ".shen": "\\* File: {} *\\",
    ".sieve": "# File: {}",
    ".sil": "// File: {}",
    ".slash": "// File: {}",
    ".ice": "// File: {}",
    ".smali": "# File: {}",
    ".tpl": "{* File: {} *}",
    ".cocci": "// File: {}",
    ".sml": "(* File: {} *)",
    ".sqf": "// File: {}",
    ".nut": "// File: {}",
    ".srl": "// File: {}",
    ".stan": "// File: {}",
    ".sc": "// File: {}",
    ".svg": "",
    ".swig": "// File: {}",
    ".t": "% File: {}",
    ".txl": "% File: {}",
    ".uno": "// File: {}",
    ".uc": "// File: {}",
    ".ur": "(* File: {} *)",
    ".vala": "// File: {}",
    ".vba": "' File: {}",
    ".vbs": "' File: {}",
    ".vcl": "# File: {}",
    ".volt": "// File: {}",
    ".wait": "# File: {}",
    ".wdl": "// File: {}",
    ".webidl": "// File: {}",
    ".whiley": "// File: {}",
    ".wlk": "// File: {}",
    ".wren": "// File: {}",
    ".x10": "// File: {}",
    ".xaml": "",
    ".xojo": "// File: {}",
    ".xsp": "",
    ".xpl": "",
    ".xq": "(: File: {} :)",
    ".xs": "/* File: {} */",
    ".xslt": "",
    ".xtend": "// File: {}",
    ".y": "/* File: {} */",
    ".yar": "// File: {}",
    ".yasnippet": "# File: {}",
    ".zap": "; File: {}",
    ".zep": "// File: {}",
    ".zimpl": "# File: {}",
    ".abap": '" File: {}',
    ".abap": "* File: {}",
    ".ada": "-- File: {}",
    ".adb": "-- File: {}",
    ".ads": "-- File: {}",
    ".apl": "⍝ File: {}",
    ".applescript": "-- File: {}",
    ".applescript": "(* File: {} *)",
    ".arc": "; File: {}",
    ".arduino": "// File: {}",
    ".asl": "// File: {}",
    ".asl": "/* File: {} */",
    ".asp": "' File: {}",
    ".asp": "REM File: {}",
    ".aspx": "<%-- File: {} --%>",
    ".ax": "// File: {}",
    ".bc": "# File: {}",
    ".b": "/* File: {} */",
    ".bmx": "' File: {}",
    ".bmx": "Rem File: {} EndRem",
    ".bro": "# File: {}",
    ".c2": "// File: {}",
    ".c3": "// File: {}",
    ".caddyfile": "# File: {}",
    ".capnp": "# File: {}",
    ".ceylon": "// File: {}",
    ".chpl": "// File: {}",
    ".clw": "! File: {}",
    ".click": "// File: {}",
    ".clp": "; File: {}",
    ".com": "$! File: {}",
    ".con": "# File: {}",
    ".cor": "'COMMENT' File: {}",
    ".cql": "-- File: {}",
    ".cql": "// File: {}",
    ".csh": "# File: {}",
    ".curry": "-- File: {}",
    ".cw": "; File: {}",
    ".cy": "// File: {}",
    ".cypher": "// File: {}",
    ".dbf": "* File: {}",
    ".dbf": "&& File: {}",
    ".dcl": "$! File: {}",
    ".dfy": "// File: {}",
    ".dfy": "/* File: {} */",
    ".di": "// File: {}",
    ".di": "/* File: {} */",
    ".diff": "# File: {}",
    ".dockerfile": "# File: {}",
    ".do": "* File: {}",
    ".do": "// File: {}",
    ".dtrace": "/* File: {} */",
    ".dwl": "// File: {}",
    ".dwl": "/* File: {} */",
    ".e": "-- File: {}",
    ".ebnf": "(* File: {} *)",
    ".ec": "// File: {}",
    ".ecl": "// File: {}",
    ".ejs": "<%# File: {} %>",
    ".el": "; File: {}",
    ".elm": "-- File: {}",
    ".elm": "{- File: {} -}",
    ".es": "// File: {}",
    ".exp": "# File: {}",
    ".f": "! File: {}",
    ".f03": "! File: {}",
    ".f08": "! File: {}",
    ".f90": "! File: {}",
    ".f95": "! File: {}",
    ".fal": "// File: {}",
    ".fal": "# File: {}",
    ".fan": "// File: {}",
    ".fan": "/* File: {} */",
    ".fth": "\\ File: {}",
    ".fth": "( File: {} )",
    ".fut": "-- File: {}",
    ".fy": "# File: {}",
    ".g": "// File: {}",
    ".g4": "// File: {}",
    ".g4": "/* File: {} */",
    ".gaml": "// File: {}",
    ".gbr": "G04 File: {}",
    ".gd": "# File: {}",
    ".gleam": "// File: {}",
    ".glsl": "// File: {}",
    ".gms": "* File: {}",
    ".gml": "// File: {}",
    ".gml": "/* File: {} */",
    ".god": "% File: {}",
    ".golo": "# File: {}",
    ".gp": "# File: {}",
    ".gps": "* File: {}",
    ".grace": "// File: {}",
    ".gradle": "// File: {}",
    ".gradle": "/* File: {} */",
    ".graphql": "# File: {}",
    ".gr": "// File: {}",
    ".gs": "// File: {}",
    ".gt": "// File: {}",
    ".hack": "// File: {}",
    ".hal": "C File: {}",
    ".haml": "-# File: {}",
    ".hbs": "{{!-- File: {} --}}",
    ".hc": "// File: {}",
    ".hc": "/* File: {} */",
    ".hcl": "# File: {}",
    ".hcl": "// File: {}",
    ".hcl": "/* File: {} */",
    ".hh": "// File: {}",
    ".hlsl": "// File: {}",
    ".hlsl": "/* File: {} */",
    ".hoc": "# File: {}",
    ".hop": "-- File: {}",
    ".hrl": "% File: {}",
    ".hs": "-- File: {}",
    ".ht": "-- File: {}",
    ".hx": "// File: {}",
    ".hy": "; File: {}",
    ".hylo": "// File: {}",
    ".ici": "// File: {}",
    ".ici": "/* File: {} */",
    ".icn": "# File: {}",
    ".idr": "-- File: {}",
    ".idr": "{- File: {} -}",
    ".ijs": "NB. File: {}",
    ".ik": "; File: {}",
    ".il": "// File: {}",
    ".inf": "! File: {}",
    ".ini": "; File: {}",
    ".ino": "// File: {}",
    ".io": "// File: {}",
    ".io": "# File: {}",
    ".ipf": "// File: {}",
    ".iss": "; File: {}",
    ".j": "// File: {}",
    ".java": "// File: {}",
    ".jcl": "//* File: {}",
    ".jl": "# File: {}",
    ".jov": '" File: {} "',
    ".js": "// File: {}",
    ".json5": "// File: {}",
    ".jsp": "<%-- File: {} --%>",
    ".jsx": "// File: {}",
    ".k": "/ File: {}",
    ".kal": "// File: {}",
    ".kk": "// File: {}",
    ".kl": "{ File: {} }",
    ".kt": "// File: {}",
    ".kts": "// File: {}",
    ".l": "# File: {}",
    ".lasso": "// File: {}",
    ".lava": "// File: {}",
    ".lean": "-- File: {}",
    ".leda": "// File: {}",
    ".less": "// File: {}",
    ".lgt": "% File: {}",
    ".li": "// File: {}",
    ".lia": "// File: {}",
    ".lisp": "; File: {}",
    ".ll": "; File: {}",
    ".logo": "; File: {}",
    ".lookml": "# File: {}",
    ".loom": "// File: {}",
    ".ls": "# File: {}",
    ".lsh": "# File: {}",
    ".lsl": "// File: {}",
    ".lua": "-- File: {}",
    ".ly": "% File: {}",
    ".m": "% File: {}",
    ".m": "/* File: {} */",
    ".m204": "* File: {}",
    ".m4": "dnl File: {}",
    ".mag": "// File: {}",
    ".magik": "## File: {}",
    ".mako": "## File: {}",
    ".max": "/* File: {} */",
    ".md": "",
    ".mel": "// File: {}",
    ".mesa": "-- File: {}",
    ".meson": "# File: {}",
    ".metal": "// File: {}",
    ".minid": "// File: {}",
    ".mint": "// File: {}",
    ".mirah": "# File: {}",
    ".ml": "(* File: {} *)",
    ".mo": "// File: {}",
    ".mojo": "# File: {}",
    ".mon": "// File: {}",
    ".moo": "; File: {}",
    ".moon": "-- File: {}",
    ".mor": "/* File: {} */",
    ".mpd": "# File: {}",
    ".mq4": "// File: {}",
    ".mtml": "<$# File: {} #$>",
    ".n": "// File: {}",
    ".n88": "// File: {}",
    ".nb": "(* File: {} *)",
    ".ncl": "; File: {}",
    ".nf": "// File: {}",
    ".ni": "[ File: {} ]",
    ".nial": "# File: {}",
    ".nim": "# File: {}",
    ".nix": "# File: {}",
    ".nix": "/* File: {} */",
    ".nlogo": "; File: {}",
    ".nr": "// File: {}",
    ".ns2": '" File: {} "',
    ".nsi": "; File: {}",
    ".nut": "// File: {}",
    ".nu": "; File: {}",
    ".obj": "# File: {}",
    ".obl": "(* File: {} *)",
    ".occ": "-- File: {}",
    ".odin": "// File: {}",
    ".opa": "// File: {}",
    ".opal": "// File: {}",
    ".ooc": "// File: {}",
    ".ops": "; File: {}",
    ".orc": "; File: {}",
    ".orc": "{- File: {} -}",
    ".orw": "|| File: {}",
    ".ox": "// File: {}",
    ".oz": "% File: {}",
    ".p": "/* File: {} */",
    ".p4": "// File: {}",
    ".pan": "# File: {}",
    ".pas": "// File: {}",
    ".pb": "; File: {}",
    ".pcode": "/* File: {} */",
    ".pde": "// File: {}",
    ".pea": "// File: {}",
    ".pel": "// File: {}",
    ".pep": "; File: {}",
    ".ph": "# File: {}",
    ".phx": "-- File: {}",
    ".php": "// File: {}",
    ".pico": "// File: {}",
    ".pig": "-- File: {}",
    ".pike": "// File: {}",
    ".pir": "# File: {}",
    ".pl": "# File: {}",
    ".pli": "/* File: {} */",
    ".plg": "/* File: {} */",
    ".pls": "-- File: {}",
    ".pml": "/* File: {} */",
    ".pm": "# File: {}",
    ".pony": "// File: {}",
    ".pov": "// File: {}",
    ".pp": "# File: {}",
    ".prc": "-- File: {}",
    ".prg": "// File: {}",
    ".prisma": "// File: {}",
    ".pro": "; File: {}",
    ".proto": "// File: {}",
    ".prt": "; File: {}",
    ".ps1": "# File: {}",
    ".ps": "% File: {}",
    ".psl": "// File: {}",
    ".pug": "// File: {}",
    ".pure": "// File: {}",
    ".purs": "-- File: {}",
    ".pwn": "// File: {}",
    ".py": "# File: {}",
    ".q": "/ File: {}",
    ".qc": "// File: {}",
    ".qml": "// File: {}",
    ".qs": "// File: {}",
    ".r": "# File: {}",
    ".raku": "# File: {}",
    ".raml": "# File: {}",
    ".rb": "# File: {}",
    ".rebol": "; File: {}",
    ".red": "; File: {}",
    ".rexx": "/* File: {} */",
    ".rg": "// File: {}",
    ".ring": "# File: {}",
    ".rkt": "; File: {}",
    ".rl": "// File: {}",
    ".robot": "# File: {}",
    ".roc": "# File: {}",
    ".rpy": "# File: {}",
    ".rq": "# File: {}",
    ".rs": "// File: {}",
    ".rsc": "// File: {}",
    ".s": "; File: {}",
    ".sa": "-- File: {}",
    ".sas": "* File: {}",
    ".sc": "// File: {}",
    ".scad": "// File: {}",
    ".scala": "// File: {}",
    ".scm": "; File: {}",
    ".sci": "// File: {}",
    ".scss": "// File: {}",
    ".sed": "# File: {}",
    ".self": '" File: {} "',
    ".sh": "# File: {}",
    ".shader": "// File: {}",
    ".shen": "\\* File: {} *\\",
    ".sil": "// File: {}",
    ".sil": "/* File: {} */",
    ".sim": "COMMENT File: {}",
    ".sis": "% File: {}",
    ".sl": "% File: {}",
    ".slash": "// File: {}",
    ".smali": "# File: {}",
    ".sml": "(* File: {} *)",
    ".sno": "* File: {}",
    ".sol": "// File: {}",
    ".sp": "// File: {}",
    ".spec": "# File: {}",
    ".spt": "* File: {}",
    ".sql": "-- File: {}",
    ".sqf": "// File: {}",
    ".sr": "# File: {}",
    ".srl": "// File: {}",
    ".st": '" File: {} "',
    ".stan": "// File: {}",
    ".str": "% File: {}",
    ".styl": "// File: {}",
    ".sv": "// File: {}",
    ".sw": "// File: {}",
    ".swift": "// File: {}",
    ".swig": "// File: {}",
    ".sym": '" File: {} "',
    ".t": "% File: {}",
    ".tacl": "== File: {}",
    ".tact": "// File: {}",
    ".talon": "# File: {}",
    ".tcl": "# File: {}",
    ".tcsh": "# File: {}",
    ".tea": "// File: {}",
    ".tex": "% File: {}",
    ".tf": "# File: {}",
    ".thrift": "// File: {}",
    ".thy": "(* File: {} *)",
    ".ti": "// File: {}",
    ".tla": "\\* File: {}",
    ".toml": "# File: {}",
    ".tom": "// File: {}",
    ".tpl": "{* File: {} *}",
    ".ts": "// File: {}",
    ".tsx": "// File: {}",
    ".txl": "% File: {}",
    ".typ": "// File: {}",
    ".u": "-- File: {}",
    ".uc": "// File: {}",
    ".uno": "// File: {}",
    ".ur": "(* File: {} *)",
    ".v": "// File: {}",
    ".vala": "// File: {}",
    ".val": "// File: {}",
    ".vba": "' File: {}",
    ".vbs": "' File: {}",
    ".vcl": "# File: {}",
    ".vert": "// File: {}",
    ".vhd": "-- File: {}",
    ".vim": '" File: {}',
    ".vip": "# File: {}",
    ".volt": "// File: {}",
    ".vue": "",
    ".vsh": "// File: {}",
    ".w": "/* File: {} */",
    ".wait": "# File: {}",
    ".wat": ";; File: {}",
    ".wdl": "// File: {}",
    ".webidl": "// File: {}",
    ".whiley": "// File: {}",
    ".wl": "(* File: {} *)",
    ".wlk": "// File: {}",
    ".wren": "// File: {}",
    ".ws": "(none) File: {}",
    ".x": "/* File: {} */",
    ".x10": "// File: {}",
    ".xaml": "",
    ".xbl": "",
    ".xojo": "// File: {}",
    ".xotcl": "# File: {}",
    ".xpl": "",
    ".xq": "(: File: {} :)",
    ".xs": "/* File: {} */",
    ".xsp": "",
    ".xtend": "// File: {}",
    ".y": "/* File: {} */",
    ".yafl": "// File: {}",
    ".yaml": "# File: {}",
    ".yar": "// File: {}",
    ".yasnippet": "# File: {}",
    ".yor": "// File: {}",
    ".zap": "; File: {}",
    ".zen": "// File: {}",
    ".zep": "// File: {}",
    ".zig": "// File: {}",
    ".zimpl": "# File: {}",
    ".zpl": "/* File: {} */",
    ".zsh": "# File: {}",
}
