# File: src/context_headers/config.py
from __future__ import annotations

# Safety: Do not process files larger than this (1MB) to prevent hangs.
MAX_FILE_SIZE_BYTES = 1024 * 1024

# Configuration: Comment styles for various extensions.
COMMENT_STYLES: dict[str, str] = {
    # Scripting / Config
    ".py": "# File: {}",
    ".yaml": "# File: {}",
    ".yml": "# File: {}",
    ".sh": "# File: {}",
    ".bash": "# File: {}",
    ".zsh": "# File: {}",
    ".toml": "# File: {}",
    ".tf": "# File: {}",
    ".tfvars": "# File: {}",
    ".dockerfile": "# File: {}",
    ".rb": "# File: {}",
    ".pl": "# File: {}",
    ".conf": "# File: {}",
    ".properties": "# File: {}",
    ".env": "# File: {}",
    ".ini": "; File: {}",
    ".ps1": "# File: {}",
    ".lua": "-- File: {}",
    ".r": "# File: {}",
    ".tcl": "# File: {}",
    ".awk": "# File: {}",
    ".jl": "# File: {}",
    ".nix": "# File: {}",
    ".hcl": "# File: {}",
    ".kcl": "# File: {}",
    ".graphql": "# File: {}",
    ".dhall": "-- File: {}",
    # Database
    ".sql": "-- File: {}",
    # Web / JS / Frontend
    ".js": "// File: {}",
    ".ts": "// File: {}",
    ".jsx": "// File: {}",
    ".tsx": "// File: {}",
    ".mjs": "// File: {}",
    ".cjs": "// File: {}",
    ".css": "/* File: {} */",
    ".scss": "/* File: {} */",
    ".less": "/* File: {} */",
    ".php": "// File: {}",
    ".elm": "-- File: {}",
    ".cljs": ";; File: {}",
    ".sol": "// File: {}",
    # Compiled / Systems
    ".java": "// File: {}",
    ".kt": "// File: {}",
    ".rs": "// File: {}",
    ".go": "// File: {}",
    ".c": "// File: {}",
    ".cpp": "// File: {}",
    ".h": "// File: {}",
    ".hpp": "// File: {}",
    ".cs": "// File: {}",
    ".swift": "// File: {}",
    ".m": "// File: {}",
    ".mm": "// File: {}",
    ".scala": "// File: {}",
    ".dart": "// File: {}",
    ".zig": "// File: {}",
    ".nim": "# File: {}",
    ".cr": "# File: {}",
    ".erl": "% File: {}",
    ".ex": "# File: {}",
    ".exs": "# File: {}",
    ".f90": "! File: {}",
    ".proto": "// File: {}",
    # HTML / Markdown / XML / Templates
    ".html": "<!-- File: {} -->",
    ".md": "<!-- File: {} -->",
    ".xml": "<!-- File: {} -->",
    ".vue": "<!-- File: {} -->",
    ".svelte": "<!-- File: {} -->",
    ".astro": "<!-- File: {} -->",
    ".aspx": "<!-- File: {} -->",
    ".cshtml": "<!-- File: {} -->",
}
