# File: src/context_headers/config.py
"""
Configuration constants for pre-commit-context-header.

This module acts as the Single Source of Truth for file size limits,
supported extensions, and their specific comment styles.
"""

from __future__ import annotations

# Safety: Do not process files larger than this (1MB) to prevent hangs.
MAX_FILE_SIZE_BYTES = 1024 * 1024

# Configuration: Comment styles for various extensions.
# Single Source of Truth.
COMMENT_STYLES: dict[str, str] = {
    # --- Shell & Scripting ---
    ".sh": "# File: {}",
    ".bash": "# File: {}",
    ".bashrc": "# File: {}",
    ".bash_profile": "# File: {}",
    ".zsh": "# File: {}",
    ".zshrc": "# File: {}",
    ".fish": "# File: {}",
    ".awk": "# File: {}",
    ".sed": "# File: {}",
    ".tcsh": "# File: {}",
    ".csh": "# File: {}",
    ".ksh": "# File: {}",
    ".pl": "# File: {}",
    ".pm": "# File: {}",
    ".tcl": "# File: {}",
    ".rb": "# File: {}",
    ".lua": "-- File: {}",
    ".rake": "# File: {}",
    ".gemspec": "# File: {}",
    ".py": "# File: {}",
    ".pyi": "# File: {}",
    ".pyw": "# File: {}",
    ".pyx": "# File: {}",
    ".coffee": "# File: {}",
    # --- Windows ---
    ".ps1": "# File: {}",
    ".psm1": "# File: {}",
    ".psd1": "# File: {}",
    ".bat": "REM File: {}",
    ".cmd": "REM File: {}",
    ".ahk": "; File: {}",
    ".au3": "; File: {}",
    ".vbs": "' File: {}",
    ".vba": "' File: {}",
    ".ws": "' File: {}",
    ".reg": "; File: {}",
    # --- Web & Frontend ---
    ".js": "// File: {}",
    ".mjs": "// File: {}",
    ".cjs": "// File: {}",
    ".ts": "// File: {}",
    ".mts": "// File: {}",
    ".cts": "// File: {}",
    ".jsx": "// File: {}",
    ".tsx": "// File: {}",
    ".vue": "<!-- File: {} -->",
    ".svelte": "<!-- File: {} -->",
    ".css": "/* File: {} */",
    ".scss": "// File: {}",
    ".sass": "// File: {}",
    ".less": "// File: {}",
    ".styl": "// File: {}",
    ".html": "<!-- File: {} -->",
    ".htm": "<!-- File: {} -->",
    ".xhtml": "<!-- File: {} -->",
    ".xml": "<!-- File: {} -->",
    ".svg": "<!-- File: {} -->",
    ".php": "// File: {}",
    ".phtml": "// File: {}",
    ".php3": "// File: {}",
    ".php4": "// File: {}",
    ".phps": "// File: {}",
    ".asp": "' File: {}",
    ".aspx": "<%-- File: {} --%>",
    ".jsp": "<%-- File: {} --%>",
    ".cfm": "<!-- File: {} -->",
    ".cfc": "<!-- File: {} -->",
    ".astro": "<!-- File: {} -->",  # Frontmatter strategy handles ---, this is fallback/HTML
    ".wasm": ";; File: {}",
    ".wat": ";; File: {}",
    # --- Backend & Compiled ---
    ".java": "// File: {}",
    ".c": "// File: {}",
    ".h": "// File: {}",
    ".cpp": "// File: {}",
    ".hpp": "// File: {}",
    ".cc": "// File: {}",
    ".hh": "// File: {}",
    ".cxx": "// File: {}",
    ".hxx": "// File: {}",
    ".cs": "// File: {}",
    ".csx": "// File: {}",
    ".go": "// File: {}",
    ".rs": "// File: {}",
    ".swift": "// File: {}",
    ".kt": "// File: {}",
    ".kts": "// File: {}",
    ".dart": "// File: {}",
    ".scala": "// File: {}",
    ".sc": "// File: {}",
    ".groovy": "// File: {}",
    ".gvy": "// File: {}",
    ".gy": "// File: {}",
    ".gsh": "// File: {}",
    ".d": "// File: {}",
    ".di": "// File: {}",
    ".val": "// File: {}",
    ".vala": "// File: {}",
    ".vapi": "// File: {}",
    ".zig": "// File: {}",
    ".v": "// File: {}",
    ".nim": "# File: {}",
    ".jl": "# File: {}",
    ".cr": "# File: {}",
    ".m": "// File: {}",  # Objective-C
    ".mm": "// File: {}",  # Objective-C++
    ".sol": "// File: {}",
    ".vy": "# File: {}",  # Vyper
    # --- Functional ---
    ".ex": "# File: {}",
    ".exs": "# File: {}",
    ".erl": "% File: {}",
    ".hrl": "% File: {}",
    ".hs": "-- File: {}",
    ".lhs": "> File: {}",
    ".clj": "; File: {}",
    ".cljs": "; File: {}",
    ".cljc": "; File: {}",
    ".edn": "; File: {}",
    ".elm": "-- File: {}",
    ".ml": "(* File: {} *)",
    ".mli": "(* File: {} *)",
    ".fs": "// File: {}",
    ".fsi": "// File: {}",
    ".fsx": "// File: {}",
    ".fsscript": "// File: {}",
    ".idr": "-- File: {}",
    ".lidr": "> File: {}",
    ".purs": "-- File: {}",
    ".r": "# File: {}",
    ".R": "# File: {}",
    ".scm": "; File: {}",
    ".ss": "; File: {}",
    ".lisp": "; File: {}",
    ".lsp": "; File: {}",
    ".rkt": "; File: {}",
    # --- Config, Data, & Infra ---
    ".yaml": "# File: {}",
    ".yml": "# File: {}",
    ".toml": "# File: {}",
    ".ini": "; File: {}",
    ".conf": "# File: {}",
    ".cfg": "# File: {}",
    ".tf": "# File: {}",
    ".tfvars": "# File: {}",
    ".hcl": "# File: {}",
    ".dockerfile": "# File: {}",
    ".gitignore": "# File: {}",
    ".dockerignore": "# File: {}",
    ".editorconfig": "# File: {}",
    ".sql": "-- File: {}",
    ".ddl": "-- File: {}",
    ".dml": "-- File: {}",
    ".graphql": "# File: {}",
    ".gql": "# File: {}",
    ".proto": "// File: {}",
    ".prisma": "// File: {}",
    ".properties": "# File: {}",
    ".makefile": "# File: {}",
    ".mk": "# File: {}",
    ".cmake": "# File: {}",
    ".json5": "// File: {}",
    ".hjson": "// File: {}",
    ".nix": "# File: {}",
    ".bicep": "// File: {}",
    # --- Documentation ---
    ".md": "<!-- File: {} -->",
    ".markdown": "<!-- File: {} -->",
    ".rst": ".. File: {}",
    ".adoc": "// File: {}",
    ".asciidoc": "// File: {}",
    ".tex": "% File: {}",
    ".sty": "% File: {}",
    ".cls": "% File: {}",
    ".org": "# File: {}",
    # --- Assembly / Low Level ---
    ".asm": "; File: {}",
    ".s": "; File: {}",
    ".inc": "; File: {}",
    ".nasm": "; File: {}",
    ".vhd": "-- File: {}",
    ".vhdl": "-- File: {}",
    ".sv": "// File: {}",
    ".svh": "// File: {}",
    # --- Modern / Niche / Other ---
    ".mojo": "# File: {}",
    ".typ": "// File: {}",
    ".gleam": "// File: {}",
    ".odin": "// File: {}",
    ".j": "// File: {}",
    ".zap": "; File: {}",
    ".zen": "// File: {}",
    ".zep": "// File: {}",
    ".zimpl": "# File: {}",
    ".zpl": "/* File: {} */",
    ".abap": '" File: {}',
    ".ada": "-- File: {}",
    ".adb": "-- File: {}",
    ".ads": "-- File: {}",
    ".agda": "-- File: {}",
    ".als": "// File: {}",
    ".ampl": "# File: {}",
    ".apl": "⍝ File: {}",
    ".applescript": "-- File: {}",
    ".arc": "; File: {}",
    ".arduino": "// File: {}",
    ".asl": "// File: {}",
    ".asy": "// File: {}",
    ".aug": "(* File: {} *)",
    ".ax": "// File: {}",
    ".bc": "# File: {}",
    ".b": "/* File: {} */",
    ".bb": "# File: {}",
    ".bcpl": "// File: {}",
    ".bmx": "' File: {}",
    ".brs": "' File: {}",
    ".bro": "# File: {}",
    ".c2": "// File: {}",
    ".c3": "// File: {}",
    ".caddyfile": "# File: {}",
    ".capnp": "# File: {}",
    ".ceylon": "// File: {}",
    ".chpl": "// File: {}",
    ".chs": "-- File: {}",
    ".click": "// File: {}",
    ".clp": "; File: {}",
    ".clw": "! File: {}",
    ".cob": "* File: {}",
    ".cbl": "* File: {}",
    ".com": "$! File: {}",
    ".con": "# File: {}",
    ".coq": "(* File: {} *)",
    ".cor": "'COMMENT' File: {}",
    ".cql": "-- File: {}",
    ".cshtml": "<!-- File: {} -->",
    ".curry": "-- File: {}",
    ".cw": "; File: {}",
    ".cy": "// File: {}",
    ".cypher": "// File: {}",
    ".dcl": "$! File: {}",
    ".dbf": "* File: {}",
    ".dfy": "// File: {}",
    ".diff": "# File: {}",
    ".do": "* File: {}",
    ".dtrace": "/* File: {} */",
    ".dwl": "// File: {}",
    ".dylan": "// File: {}",
    ".e": "-- File: {}",
    ".ebnf": "(* File: {} *)",
    ".ec": "// File: {}",
    ".ecl": "// File: {}",
    ".ejs": "<%# File: {} %>",
    ".el": "; File: {}",
    ".es": "// File: {}",
    ".exp": "# File: {}",
    ".f": "! File: {}",
    ".f90": "! File: {}",
    ".for": "! File: {}",
    ".f03": "! File: {}",
    ".f08": "! File: {}",
    ".f95": "! File: {}",
    ".factor": "! File: {}",
    ".fal": "// File: {}",
    ".fan": "// File: {}",
    ".flow": "// File: {}",
    ".fth": "\\ File: {}",
    ".fut": "-- File: {}",
    ".fy": "# File: {}",
    ".g": "// File: {}",
    ".g4": "// File: {}",
    ".gaml": "// File: {}",
    ".gap": "# File: {}",
    ".gbr": "G04 File: {}",
    ".gd": "# File: {}",
    ".glsl": "// File: {}",
    ".vert": "// File: {}",
    ".frag": "// File: {}",
    ".gms": "* File: {}",
    ".gml": "// File: {}",
    ".god": "% File: {}",
    ".golo": "# File: {}",
    ".gp": "# File: {}",
    ".gps": "* File: {}",
    ".grace": "// File: {}",
    ".gradle": "// File: {}",
    ".gr": "// File: {}",
    ".gs": "// File: {}",
    ".gt": "// File: {}",
    ".hack": "// File: {}",
    ".hal": "C File: {}",
    ".haml": "-# File: {}",
    ".hbs": "{{!-- File: {} --}}",
    ".handlebars": "{{!-- File: {} --}}",
    ".hc": "// File: {}",
    ".hlsl": "// File: {}",
    ".hoc": "# File: {}",
    ".hop": "-- File: {}",
    ".ht": "-- File: {}",
    ".hx": "// File: {}",
    ".hy": "; File: {}",
    ".hylo": "// File: {}",
    ".ice": "// File: {}",
    ".ici": "// File: {}",
    ".icn": "# File: {}",
    ".ijs": "NB. File: {}",
    ".ik": "; File: {}",
    ".il": "// File: {}",
    ".inf": "! File: {}",
    ".ino": "// File: {}",
    ".io": "// File: {}",
    ".ipf": "// File: {}",
    ".iss": "; File: {}",
    ".jcl": "//* File: {}",
    ".jov": '" File: {} "',
    ".k": "/ File: {}",
    ".kal": "// File: {}",
    ".kk": "// File: {}",
    ".kl": "{ File: {} }",
    ".krl": "; File: {}",
    ".l": "# File: {}",
    ".lasso": "// File: {}",
    ".lava": "// File: {}",
    ".lean": "-- File: {}",
    ".leda": "// File: {}",
    ".lgt": "% File: {}",
    ".li": "// File: {}",
    ".lia": "// File: {}",
    ".ll": "; File: {}",
    ".logo": "; File: {}",
    ".lookml": "# File: {}",
    ".loom": "// File: {}",
    ".ls": "# File: {}",
    ".lsh": "# File: {}",
    ".lsl": "// File: {}",
    ".ly": "% File: {}",
    ".m204": "* File: {}",
    ".m4": "dnl File: {}",
    ".mag": "// File: {}",
    ".magik": "## File: {}",
    ".mako": "## File: {}",
    ".max": "/* File: {} */",
    ".mel": "// File: {}",
    ".mesa": "-- File: {}",
    ".meson": "# File: {}",
    ".metal": "// File: {}",
    ".minid": "// File: {}",
    ".mint": "// File: {}",
    ".mirah": "# File: {}",
    ".mo": "// File: {}",
    ".mod": "(* File: {} *)",
    ".mon": "// File: {}",
    ".moo": "; File: {}",
    ".moon": "-- File: {}",
    ".mor": "/* File: {} */",
    ".mpd": "# File: {}",
    ".mq4": "// File: {}",
    ".mq5": "// File: {}",
    ".mtml": "<$# File: {} #$>",
    ".mustache": "{{! File: {} }}",
    ".n": "// File: {}",
    ".n88": "// File: {}",
    ".nb": "(* File: {} *)",
    ".ncl": "; File: {}",
    ".nf": "// File: {}",
    ".ni": "[ File: {} ]",
    ".nial": "# File: {}",
    ".nlogo": "; File: {}",
    ".nr": "// File: {}",
    ".ns2": '" File: {} "',
    ".nsi": "; File: {}",
    ".nu": "; File: {}",
    ".nut": "// File: {}",
    ".obj": "# File: {}",
    ".obl": "(* File: {} *)",
    ".occ": "-- File: {}",
    ".ooc": "// File: {}",
    ".opa": "// File: {}",
    ".opal": "// File: {}",
    ".ops": "; File: {}",
    ".orc": "; File: {}",
    ".orw": "|| File: {}",
    ".ox": "// File: {}",
    ".oz": "% File: {}",
    ".p": "/* File: {} */",
    ".p4": "// File: {}",
    ".pan": "# File: {}",
    ".pas": "// File: {}",
    ".pb": "; File: {}",
    ".pbl": "// File: {}",
    ".pcode": "/* File: {} */",
    ".pde": "// File: {}",
    ".pea": "// File: {}",
    ".pel": "// File: {}",
    ".pep": "; File: {}",
    ".ph": "# File: {}",
    ".phx": "-- File: {}",
    ".pico": "// File: {}",
    ".pig": "-- File: {}",
    ".pike": "// File: {}",
    ".pir": "# File: {}",
    ".pli": "/* File: {} */",
    ".plg": "/* File: {} */",
    ".pls": "-- File: {}",
    ".pml": "/* File: {} */",
    ".pony": "// File: {}",
    ".pov": "// File: {}",
    ".pp": "# File: {}",
    ".prc": "-- File: {}",
    ".prg": "// File: {}",
    ".pro": "; File: {}",
    ".prt": "; File: {}",
    ".ps": "% File: {}",
    ".psc": "; File: {}",
    ".psl": "// File: {}",
    ".pug": "// File: {}",
    ".jade": "// File: {}",
    ".pure": "// File: {}",
    ".pwn": "// File: {}",
    ".q": "/ File: {}",
    ".qc": "// File: {}",
    ".qml": "// File: {}",
    ".qs": "// File: {}",
    ".raku": "# File: {}",
    ".raml": "# File: {}",
    ".ratfor": "# File: {}",
    ".razor": "@* File: {} *@ ",
    ".rebol": "; File: {}",
    ".red": "; File: {}",
    ".rexx": "/* File: {} */",
    ".rg": "// File: {}",
    ".ring": "# File: {}",
    ".rl": "// File: {}",
    ".robot": "# File: {}",
    ".roc": "# File: {}",
    ".rpy": "# File: {}",
    ".rq": "# File: {}",
    ".rsc": "// File: {}",
    ".sa": "-- File: {}",
    ".sas": "* File: {}",
    ".scad": "// File: {}",
    ".sci": "// File: {}",
    ".self": '" File: {} "',
    ".shader": "// File: {}",
    ".shen": "\\* File: {} *\\",
    ".sil": "// File: {}",
    ".sim": "COMMENT File: {}",
    ".sis": "% File: {}",
    ".sl": "% File: {}",
    ".slash": "// File: {}",
    ".smali": "# File: {}",
    ".sml": "(* File: {} *)",
    ".sno": "* File: {}",
    ".sp": "// File: {}",
    ".spec": "# File: {}",
    ".spt": "* File: {}",
    ".sqf": "// File: {}",
    ".sr": "# File: {}",
    ".srl": "// File: {}",
    ".st": '" File: {} "',
    ".stan": "// File: {}",
    ".str": "% File: {}",
    ".sw": "// File: {}",
    ".swig": "// File: {}",
    ".sym": '" File: {} "',
    ".t": "% File: {}",
    ".tacl": "== File: {}",
    ".tact": "// File: {}",
    ".talon": "# File: {}",
    ".tea": "// File: {}",
    ".thrift": "// File: {}",
    ".thy": "(* File: {} *)",
    ".ti": "// File: {}",
    ".tla": "\\* File: {}",
    ".tom": "// File: {}",
    ".tpl": "{* File: {} *}",
    ".twig": "{# File: {} #}",
    ".txl": "% File: {}",
    ".u": "-- File: {}",
    ".uc": "// File: {}",
    ".uno": "// File: {}",
    ".ur": "(* File: {} *)",
    ".vcl": "# File: {}",
    ".vim": '" File: {}',
    ".vip": "# File: {}",
    ".volt": "// File: {}",
    ".vsh": "// File: {}",
    ".w": "/* File: {} */",
    ".wait": "# File: {}",
    ".wdl": "// File: {}",
    ".webidl": "// File: {}",
    ".whiley": "// File: {}",
    ".wl": "(* File: {} *)",
    ".wlk": "// File: {}",
    ".wren": "// File: {}",
    ".x": "/* File: {} */",
    ".x10": "// File: {}",
    ".xaml": "<!-- File: {} -->",
    ".xbl": "<!-- File: {} -->",
    ".xojo": "// File: {}",
    ".xotcl": "# File: {}",
    ".xpl": "<!-- File: {} -->",
    ".xq": "(: File: {} :)",
    ".xs": "/* File: {} */",
    ".xsp": "<!-- File: {} -->",
    ".xslt": "<!-- File: {} -->",
    ".xtend": "// File: {}",
    ".y": "/* File: {} */",
    ".yafl": "// File: {}",
    ".yar": "// File: {}",
    ".yasnippet": "# File: {}",
    ".yor": "// File: {}",
    ".🔥": "# File: {}",
}
